### ISSUE TITLE
issue with google login

### ISSUE THREAD

**Issue by mamadza** [yiisoft/yii2-authclient#274]
Hi I have problem with login with google 

### What steps will reproduce the problem?
login with google 

### What do you get instead?
![Untitled](https://user-images.githubusercontent.com/12842935/58243733-7552af00-7d66-11e9-8126-96eb4d021318.png)

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.19
| Yii Auth Client version | 2.2.2
| Yii HTTP Client version | 2.0.11
| PHP version             | 7.2
| Operating system        | ubuntu 18.04

**Comment by mamadza** [comment]
why this issuse is close? I search there is bug in previous release and I have this error now , my app work correctly in past

**Comment by machour** [comment]
I thought that you were having troubles configuring your redirect_uri in the Google Console.

Can you give more details about "in the past"?

* What yii2-authclient were you using when it worked?
* Can you try downgrading yii2-authclient and see if a past version works?
* Can you double check your redirect_uri configuration? (don't know if it changed since Google+ was abandoned)

**Comment by ianguerit** [comment]
We were seeing similar problems with latest library, only happening for some users.
Issue was getting bad request 400, invalid request_uri
Traced the issue to the redirect uri including other parameters for session_state, prompt, hd and authuser which weren't in the valid request_uri - these weren't being included for users where login was working.
Not sure of the cause, suspect Google might be getting stricter on validating the request_uri 

To resolve added the following in to Oauth2.php:defaultReturnUrl()
unset($params['session_state']);
unset($params['prompt']);
unset($params['hd']);
unset($params['authuser']);

**Comment by des1roer** [comment]
dont`t work

**Comment by des1roer** [comment]
![image](https://user-images.githubusercontent.com/10970793/59744775-bc13c600-928c-11e9-9b85-d3a6deefba19.png)

**Comment by t-kanstantsin** [comment]
Have same error. Full list of return query params (in my case):

- state
- code
- scope
- authuser
- session_state
- prompt

So @des1roer, I see you do not have `unset($params['scope']);`. It is in code https://github.com/yiisoft/yii2-authclient/blob/master/src/OAuth2.php#L192 but you deleted it occasionaly I think.

**Comment by jokamax** [comment]
Same problem here.
I have to add : 
unset($params['session_state']);
unset($params['prompt']);
unset($params['hd']);
unset($params['authuser']);
And this seem to work now.

**Comment by djagya** [comment]
Solved by extending the Google class:

```php
class Google extends \yii\authclient\clients\Google
{
    protected function defaultReturnUrl()
    {
        $params = Yii::$app->getRequest()->getQueryParams();
        $remove = ['code', 'state', 'scope', 'session_state', 'prompt', 'hd', 'authuser'];
        // Safely remove all values by the key.
        $params = array_diff_key($params, array_flip($remove));
        $params[0] = Yii::$app->controller->getRoute();

        return Yii::$app->getUrlManager()->createAbsoluteUrl($params);
    }
}
```

**Comment by rockman84** [comment]
suddenly got same issue "error": "redirect_uri_mismatch" 

> Solved by extending the Google class:
> 
> ```
> class Google extends \yii\authclient\clients\Google
> {
>     protected function defaultReturnUrl()
>     {
>         $params = Yii::$app->getRequest()->getQueryParams();
>         $remove = ['code', 'state', 'scope', 'session_state', 'prompt', 'hd', 'authuser'];
>         // Safely remove all values by the key.
>         $params = array_diff_key($params, array_flip($remove));
>         $params[0] = Yii::$app->controller->getRoute();
> 
>         return Yii::$app->getUrlManager()->createAbsoluteUrl($params);
>     }
> }
> ```

still not working

**Comment by spinitron** [comment]
@rockman84 did you configure your app's auth client to use your version? e.g.

```php
        'authClientCollection' => [
            'clients' => [
                'google' => [
                    'class' => \your\name\space\Google::class,
```

**Comment by d3artagnan** [comment]
+1

Looks like there is new params returned by google, that needs to be unset
@des1roer solution is working

**Comment by rockman84** [comment]
> @rockman84 did you configure your app's auth client to use your version? e.g.
> 
> ```
>         'authClientCollection' => [
>             'clients' => [
>                 'google' => [
>                     'class' => \your\name\space\Google::class,
> ```
`namespace app\components\google;

class GoogleAuthClient extends \yii\authclient\clients\Google
{
    protected function defaultReturnUrl()
    {
        $params = Yii::$app->getRequest()->getQueryParams();
        $remove = ['code', 'state', 'scope', 'session_state', 'prompt', 'hd', 'authuser'];
        // Safely remove all values by the key.
        $params = array_diff_key($params, array_flip($remove));
        $params[0] = Yii::$app->controller->getRoute();

        return Yii::$app->getUrlManager()->createAbsoluteUrl($params);
    }
}
`

`
'google' => [
                    'class' => 'app\components\google\GoogleAuthClient',
                    'clientId' => 'XXXX',
                    'clientSecret' => 'XXXXX',
                ],
`
yes i did. but still not working

**Comment by tom--** [comment]
@rockman84 you can probably update to master and remove this hack now. See PR #278

**Comment by tom--** [comment]
Fixed by #278
